# Generated by Django 4.0 on 2022-03-24 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
        ('inventario', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Publicación activa'), ('PP', 'Publicación pausada'), ('ND', 'Producto No disponible'), ('PA', 'Producto Agotado'), ('PR', 'Producto rebajado'), ('EG', 'Envío gratis')], default='AC', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_client', to='perfiles.userbase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('upb', 'Unpublished'), ('pb', 'Published')], default='pb', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='perfiles.userbase')),
                ('inventory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='inventario.inventory')),
            ],
            options={
                'ordering': ('-published',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
