# Generated by Django 4.0 on 2022-03-27 00:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('upb', 'Unpublished'), ('pb', 'Published')], default='pb', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='perfiles.userbase')),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventorys', to='inventario.inventory')),
            ],
            options={
                'ordering': ('-published',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
