# Generated by Django 4.0 on 2022-03-07 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
        ('products', '0003_alter_media_options'),
        ('inventario', '0002_alter_inventory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Publicación activa'), ('PP', 'Publicación pausada'), ('ND', 'Producto No disponible'), ('PA', 'Producto Agotado'), ('PR', 'Producto rebajado'), ('EG', 'Envío gratis')], default='AC', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_client', to='perfiles.userbase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('upb', 'Unpublished'), ('pb', 'Published')], default='pb', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_posts', to='perfiles.userbase')),
                ('category', mptt.fields.TreeManyToManyField(to='products.Category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.media', verbose_name='Producto')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.inventory', verbose_name='Inventory')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
