# Generated by Django 4.0 on 2022-04-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='billing_address',
            field=models.CharField(max_length=150, verbose_name='Dirección de facturacion'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shipping_address',
            field=models.CharField(max_length=150, verbose_name='Dirección de envío'),
        ),
    ]
