# Generated by Django 4.0 on 2022-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterField(
            model_name='address',
            name='oficina_address',
            field=models.CharField(max_length=150, verbose_name='Dirección 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='residencia_address',
            field=models.CharField(max_length=150, verbose_name='Dirección 1'),
        ),
    ]
