# Generated by Django 4.0 on 2022-03-30 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_alter_address_options_alter_address_oficina_address_and_more'),
        ('cart', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfiles.userbase'),
        ),
    ]
