# Generated by Django 3.2.9 on 2021-12-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='product_attribute',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ManyToManyField(related_name='favorite_product', to='products.Product'),
        ),
    ]
