# Generated by Django 4.0 on 2022-03-27 03:24

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(to='products.Category', verbose_name='category'),
        ),
    ]
