# Generated by Django 4.0 on 2022-03-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211207_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('product',), 'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
    ]
